name: Count Up Value in JSON and Modify File  
  
on:  
  push:  
    branches:
      - main
  
jobs:  
  count-up-value-in-json-and-modify-file:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2

      - name: Create Branch
        run: git checkout -b new-branch
  
      - name: Read value from JSON  
        id: read-value  
        run: |  
          VALUE=$(jq '.latest' release.json)  
          echo "::set-output name=value::${VALUE}"  
  
      - name: Parse version number
        id: parse-version
        run: |
          IFS='.' read -r -a VERSION_PARTS <<< "${{ steps.read-value.outputs.value }}"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          echo "::set-output name=major::${MAJOR}"
          echo "::set-output name=minor::${MINOR}"
          echo "::set-output name=patch::${PATCH}"

      - name: Increment version number
        id: increment-version
        run: |
          MAJOR="${{ steps.parse-version.outputs.major }}"
          MINOR="${{ steps.parse-version.outputs.minor }}"
          PATCH="${{ steps.parse-version.outputs.patch }}"
          PATCH=$((PATCH + 1))
          echo "::set-output name=major::${MAJOR}"
          echo "::set-output name=minor::${MINOR}"
          echo "::set-output name=patch::${PATCH}"

      - name: Modify JSON
        run: |
          NEW_VALUE="${{ steps.increment-version.outputs.major }}.${{ steps.increment-version.outputs.minor }}.${{ steps.increment-version.outputs.patch }}"
          jq '.latest = $new_value' --arg new_value "$NEW_VALUE" release.json > release.json.tmp
          mv release.json.tmp release.json
  
      - name: Create pull request  
        uses: peter-evans/create-pull-request@v6
        with:  
          commit-message: "Count up value in data.json"  
          branch: new-release 
          title: "New release"  
          body: "This is an automated pull request."
