name: Create Pull Request for new Release
  
on:  
  on:
  schedule:
    - cron: '0 10 * * 0/2' 
  push:  
    branches:
      - test-create-release
  
jobs:  
  count-up-value-in-json-and-modify-file:  
    runs-on: self-hosted
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v3
  
      - name: Read value from JSON  
        id: read-value  
        run: |  
          VALUE=$(jq -r '.latest' release.json)
          echo "value=${VALUE}" >> $GITHUB_ENV 
          IFS='.' read -r -a VERSION_PARTS <<< "${VALUE}"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          PATCH=$((PATCH + 1))
          echo "MAJOR=${MAJOR}" >> $GITHUB_ENV 
          echo "MINOR=${MINOR}" >> $GITHUB_ENV 
          echo "PATCH=${PATCH}" >> $GITHUB_ENV

      - name: Modify JSON
        run: |
          NEW_VALUE="${MAJOR}.${MINOR}.${PATCH}"
          jq '.latest = $new_value' --arg new_value "$NEW_VALUE" release.json > release.json.tmp
          mv release.json.tmp release.json
  
      - name: Create pull request  
        uses: peter-evans/create-pull-request@v6
        with:  
          commit-message: "Count up value in data.json"  
          branch: new-release 
          title: "New release"  
          body: "This is an automated pull request."
