name: Count Up Value in JSON and Modify File  
  
on:  
  push:  
    branches:
      - main
  
jobs:  
  count-up-value-in-json-and-modify-file:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2
  
      - name: Read value from JSON  
        id: read-value  
        run: |  
          VALUE=$(jq '.latest' release.json)
          echo "value=${VALUE}" >> $GITHUB_OUTPUT 
          IFS='.' read -r -a VERSION_PARTS <<< "${VALUE}"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          PATCH=$((PATCH + 1))
          echo "major=${MAJOR}" >> $GITHUB_OUTPUT 
          echo "minor=${MINOR}" >> $GITHUB_OUTPUT 
          echo "patch=${PATCH}" >> $GITHUB_OUTPUT

      - name: Modify JSON
        run: |
          NEW_VALUE="${{ steps.increment-version.outputs.major }}.${{ steps.increment-version.outputs.minor }}.${{ steps.increment-version.outputs.patch }}"
          jq '.latest = $new_value' --arg new_value "$NEW_VALUE" release.json > release.json.tmp
          mv release.json.tmp release.json
  
      - name: Create pull request  
        uses: peter-evans/create-pull-request@v6
        with:  
          commit-message: "Count up value in data.json"  
          branch: new-release 
          title: "New release"  
          body: "This is an automated pull request."
