name: Check if anything has been merged into master  
  
on:  
  push:
    branch:
      - versuch
  
jobs:  
  check-merged:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v3 
  
      - name: Create pull request
        if: github.ref == 'refs/heads/main' && (fromJSON(github.event.head_commit.timestamp) | mktime) > (now - duration('14d')).seconds)  
        run: echo "Yes"