name: Check if anything has been merged into master  
  
on:  
  push:
    branch:
      - versuch
  
jobs:  
  check-merged:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v3 
      - name: Get timestamp of latest commit on master  
        id: latest_commit  
        run: |  
          LATEST_COMMIT=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/main" | jq -r '.commit.committer.date')  
          echo "timestamp=$(date -d ${LATEST_COMMIT//\"} +"%s")"
          echo "timestamp=$(date -d ${LATEST_COMMIT//\"} +"%s")"" >> $GITHUB_ENV 
