name: Check if anything has been merged into master
on:
  push:
    branches:
      - versuch
  
jobs:  
  check-merged:  
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code  
        uses: actions/checkout@v3 
        with:
          ref: "main"

      - name: Get timestamp of latest commit on master
        id: date_check
        run: |
          fourteen_day_ago=$(date +%s -d "7 day ago")
          last_commit=$(git show -s --format=%ct)
          
          echo "last_commit: ${last_commit}"
          echo "past_timestamp: ${fourteen_day_ago}"

          if [[ last_commit -gt fourteen_day_ago ]]; then
            echo "create_new_release=true" >> $GITHUB_OUTPUT
          else
            echo "create_new_release=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Read value from JSON  
        if: steps.date_check.outputs.create_new_release == 'true'
        run: |
          echo "New PR"
      - name: Read value from JSON  2
        if: steps.date_check.outputs.create_new_release == 'false'
        run: |
          echo "No new PR"
