name: Check if anything has been merged into master
on:
  push:
    branches:
      - versuch
  
jobs:  
  check-merged:  
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code  
        uses: actions/checkout@v3 
        with:
          ref: "versuch"

      - name: Get timestamp of latest commit on master
        id: date_check
        run: |
          14_day_ago="1707128131"
          last_commit="1708334034"
          if [[ last_commit > 14_day_ago ]]; then
            echo "create_new_release=true" >> $GITHUB_OUTPUT
          else
            echo "create_new_release=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Read value from JSON  
        if: steps.date_check.outputs.create_new_release == 'true'
        run: |
          echo "New PR"
      - name: Read value from JSON  
        if: steps.date_check.outputs.create_new_release == 'false'
        run: |
          echo "No new PR"
